---
DOCKER_DEPS:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
DOCKER_TOOLS:
  - docker-ce
  - docker-ce-cli
  - containerd.io
PYTHON_PKGS:
  - deepdiff
  - kubernetes==22.6.0
  - exrex
  - jsonschema
  - jsonpatch
  - pandas
TMPFS_SIZE: 140G